workflows:
  ios-debug:
    name: iOS Debug (No Signing)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        APPLE_ID_EMAIL: nvsands@gmail.com
        APPLE_ID_PASSWORD: xvnw-czzq-jlrm-swpd
        APPLE_TEAM_ID: A983KC345J
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Install CocoaPods
        script: cd ios && pod install
      - name: Build Debug App (No Signing)
        script: flutter build ios --debug --no-codesign
      - name: Package for AltStore
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r DoorbirdApp.zip Payload
    artifacts:
      - DoorbirdApp.zip